'use strict';

const {dialogflow} = require('actions-on-google');
const functions    = require('firebase-functions');

function Proposition( oneliner, summary, yes, no, pro, con, for_, against ) {
    this.oneliner = oneliner;
    this.summary  = summary;
    this.yes      = yes;
    this.no       = no;
    this.pro      = pro;
    this.con      = con;
    this['for']   = for_;
    this.against  = against;
    this.say_property = function( conv, property_name ) {
	if( this.hasOwnProperty(property_name) ) {
	    conv.ask(this[property_name]);
	}
	else {
	    conv.ask(`Sorry, I do not know about ${property_name}`);
	}
    }
}
const propositions = {
    68 : new Proposition(
	"AUTHORIZES BONDS FUNDING PARKS, NATURAL RESOURCES PROTECTION, CLIMATE ADAPTATION, WATER QUALITY AND SUPPLY, AND FLOOD PROTECTION",
	"Authorizes $4 billion in general obligation bonds for: parks, natural resources protection, climate adaptation, water quality "+
	    "and supply, and flood protection. Fiscal Impact: Increased state bond repayment costs averaging $200 million annually over "+
	    "40 years. Local government savings for natural resourcesrelated projects, likely averaging several tens of millions of dollars annually over the next few decades.",
	"A YES vote on this measure means: The state could sell $4.1 billion in general obligation bonds to fund various natural resourcesrelated "+
	    "programs such as for habitat conservation, parks, and water-related projects.",
	"A NO vote on this measure means: The state could not sell $4.1 billion in general obligation bonds to fund various natural resourcesrelated programs.",
	"California faces droughts, wildfires, floods, and other challenges to our water and natural resources. YES ON 68: Invests in natural resources and "+
	    "disaster prevention, cleans up contaminated drinking water, increases local water supplies, provides safe parks for children and future generations. Annual "+
	    "audits ensure accountability. American Lung Association in California, California Chamber of Commerce, The Nature Conservancy, agree: www.YES68CA.com",
	"I’m not here to tell you that addressing drought, water, parks, climate, coastal protection, and outdoor access is wrong. Borrowing for "+
	    "them is wrong. California has enough debt. It has the worst balance sheet of all 50 states. The last thing the State of California needs is more debt!",
	"Ann Newton. Californians for Clean Water and Safe Parks.\n"+
	    "12711 Ventura Blvd.,\n"+
	    "Suite 170\n"+
	    "Los Angeles, CA 91604\n"+
	    "(818) 760-2121\n"+
	    "anewton@fionahuttonassoc.com\n"+
	    "www.YES68CA.com",
	"Lance Christensen, California State Senator. John MW Moorlach.\n"+
	    "Capitol Room 2048\n"+
	    "Sacramento, CA 95814\n"+
	    "(916) 651-4037\n"+
	    "lance.christensen@sen.ca.gov\n"+
	    "moorlach.ca.gov"),
    69 : new Proposition(
	"REQUIRES THAT CERTAIN NEW TRANSPORTATION REVENUES BE USED FOR TRANSPORTATION PURPOSES. LEGISLATIVE CONSTITUTIONAL AMENDMENT",
	"Requires that certain revenues generated by a 2017 transportation funding law be used only for transportation purposes and generally prohibits Legislature from diverting "+
	    "funds to other purposes. Fiscal Impact: No direct effect on the amount of state and local revenues or costs but could affect how some monies are spent.",
	"A YES vote on this measure means: The Legislature will be required under the State Constitution to continue to spend revenues from recently enacted fuel "+
	    "taxes and vehicle fees on transportation purposes (such as repairing roads and improving transit).",
	"A NO vote on this measure means: The Legislature in the future could change current law, allowing it to spend a portion of the revenues from recently enacted fuel "+
	    "taxes and vehicle fees on purposes other than transportation.",
	"Prop. 69 guarantees existing transportation taxes can ONLY be used for transportation improvement projects. It prevents the legislature from redirecting these funds for "+
	    "non-transportation purposes. Prop. 69 protects taxpayers. Does NOT raise taxes. Supported by League of Women Voters California, California Chamber of Commerce, "+
	    "California NAACP, Congress of California Seniors.",
	"Sacramento’s broken promises have led to a rundown, outdated, and congested transportation system throughout California. Proposition 69 protectstransportation money that will "+
	    "not fix or build any new roads. Proposition 69 fails to protect more than $1 Billion in gas tax revenues. Vote NO on Proposition 69",
	"Coalition to Protect Local Transportation Improvements\n"+
	    "(866) 285-9833\n"+
	    "info@YesProp69.com\n"+
	    "YesProp69.com",
	"Katie Masingale\n"+
	    "California State Assembly,\n"+
	    "Office of Assemblyman\n"+
	    "Frank Bigelow\n"+
	    "California State Capitol,\n"+
	    "Suite 4158\n"+
	    "Sacramento, CA 95814\n"+
	    "(916) 319-2005\n"+
	    "Katie.Masingale@asm.ca.gov\n"+
	    "ASM.CA.GOV/Bigelow"),
    70 : new Proposition(
	"REQUIRES LEGISLATIVE SUPERMAJORITY VOTE APPROVING USE OF CAP-AND-TRADE RESERVE FUND. LEGISLATIVE CONSTITUTIONAL AMENDMENT.",
	"Beginning in 2024, requires that cap-and-trade revenues accumulate in a reserve fund until the Legislature, by a two-thirds majority, authorizes use of the revenues. "+
	    "Fiscal Impact: Beginning in 2024, potential temporary increase in state sales tax revenue, ranging from none to a few hundred million dollars annually, and possible "+
	    "changes in how revenue from sale of greenhouse gas emission permits is spent.",
	"A YES vote on this measure means: Beginning on January 1, 2024, revenue collected from the sale of state greenhouse gas emission permits would be deposited into a new special "+
	    "fund. These deposits would continue until the effective date of a bill that spends money from that fund, passed with a two-thirds vote of each house of the Legislature. The "+
	    "current state sales tax exemption for manufacturing and certain other equipment would be suspended during the same period that auction revenue is deposited into the "+
	    "special fund",
	"A YES vote on this measure means: Beginning on January 1, 2024, revenue collected from the sale of state greenhouse gas emission permits would be deposited into a new special "+
	    "fund. These deposits would continue until the effective date of a bill that spends money from that fund, passed with a two-thirds vote of each house of the Legislature. The "+
	    "current state sales tax exemption for manufacturing and certain other equipment would be suspended during the same period that auction revenue is deposited into the "+
	    "special fund",
	"Proposition 70 is SUPPORTED BY DEMOCRATS AND REPUBLICANS, LABOR, BUSINESS; AND FARMERS who want to protect our environment and grow our economy. Forcing a two-thirds "+
	    "legislative vote ensures MONEY IS SPENT WISELY FOR HIGH PRIORITY PROGRAMS THAT BENEFIT ALL CALIFORNIANS AND THAT IT IS NOT DIVERTED FOR PET PROJECTS.\n"+
	    "www.YesOnProposition70.com",
	"Proposition 70 grew out of an oil industry-backed effort to weaken the state’s premier program to curb harmful air pollution and climate change. It will increase legislative "+
	    "gridlock, hurt public health, and empower antienvironmental special interests. 35 environmental organizations and the League of Women Voters California oppose Proposition 70.",
	"Yes on Proposition 70\n"+
	    "Info@YesonProposition70.com\n"+
	    "www.YesOnProposition70.com",
	"info@stopprop70.org\n"+
	    "www.stopprop70.org"
    ),
    71 : new Proposition(
	"SETS EFFECTIVE DATE FOR BALLOT MEASURES. LEGISLATIVE CONSTITUTIONAL AMENDMENT.",
	"Provides that ballot measures approved by a majority of voters shall take effect five days after the Secretary of State certifies the results of the election. "+
	    "Fiscal Impact: Likely little or no effect on state and local finances.",
	"A YES vote on this measure means: Most state ballot measures (also called propositions) would take effect after the statewide vote has been counted and certified—about "+
	    "six weeks after Election Day.",
	"A NO vote on this measure means: Most state ballot measures would continue to take effect the day after Election Day.",
	"Proposition 71 will prevent confusion over implementation dates for ballot measures in future elections. Currently, measures are effective the day after the "+
	    "election, unless otherwise specified. Proposition 71 will provide a clear point at which measures shall be effective, eliminating confusion when "+
	    "election outcomes have yet to be certified.",
	"Although surely well-intended, Proposition 71 is unnecessary and would prevent future ballot measures from (retroactively) taking effect “the day after the "+
	    "election” as is currently permitted by the California Constitution. Sometimes it is important that changes in the law made by voters apply as soon as possible.",
	"Kevin Mullin\n"+
	    "CA State Assembly\n"+
	    "Speaker pro Tempore\n"+
	    "Rm. 3160 CA State Capitol\n"+
	    "Sacramento, CA 95814\n"+
	    "(916) 319-2022\n"+
	    "Kevin.Mullin@asm.ca.gov",
	"Gary Wesley\n"+
	    "gary.wesley@yahoo.com"
    ),
    72 : new Proposition(
	"PERMITS LEGISLATURE TO EXCLUDE NEWLY CONSTRUCTED RAIN-CAPTURE SYSTEMS FROM PROPERTY-TAX REASSESSMENT REQUIREMENT. LEGISLATIVE CONSTITUTIONAL AMENDMENT.",
	"Permits Legislature to allow construction of rain-capture systems, completed on or after January 1, 2019, without requiring property-tax reassessment. Fiscal Impact: Probably "+
	    "minor reduction in annual property tax revenues to localgovernments.",
	"A YES vote on this measure means: Installing a system to collect and store rainwater on a property could not result in ahigher property tax bill.",
	"A NO vote on this measure means: Installing a system to collect and store rainwater on a property could result in a higher property tax bill.",
	"Proposition 72 will prevent a property tax increase on homeowners who install rainwater recycling systems that benefit our entire state. Eliminating this tax "+
	    "penalty will preserve precious drinking water; help fish and wildlife; lower water bills. People shouldn’t pay a tax penalty for conserving water. Yes on Proposition 72.",
	"No argument against Proposition 72 was submitted.",
	"Steven Glazer\n"+
	    "California State Senate\n"+
	    "21C Orinda Wy. #111\n"+
	    "Orinda, CA 94563\n"+
	    "Steven@SaveCaWater.org\n"+
	    "SaveCaWater.org",
	"No contact information was provided"
    )
};
function handle_proposition_request( conv, args, property_name ) {
    if( args.number==='' ) {
	if( conv.data && conv.data.proposition && propositions.hasOwnProperty(conv.data.proposition) ) {
	    propositions[conv.data.proposition].say_property(conv,property_name);
	}
	else {
	    conv.ask("Please specify the proposition number");
	}
    }
    else if( propositions.hasOwnProperty(Number(args.number)) ) {
	conv.data.proposition = Number(args.number);
	propositions[conv.data.proposition].say_property(conv,property_name);
    }
    else {
	conv.ask(`Proposition ${args.number} is unknown to me`);
    }
}
const app = dialogflow({debug:true});
app.intent('proposition',( conv, args ) => {
    handle_proposition_request(conv,args,'oneliner');
}).intent('proposition_summary',( conv, args ) => {
    handle_proposition_request(conv,args,'summary');
}).intent('proposition_yes_no',( conv, args ) => {
    handle_proposition_request(conv,args,args.yes_or_no);
}).intent('proposition_pro_con',( conv, args ) => {
    handle_proposition_request(conv,args,args.pro_or_con);
}).intent('proposition_for_against',( conv, args ) => {
    handle_proposition_request(conv,args,args.for_or_against);
}).intent('goodbye',( conv,args ) => {
    conv.close();
});

exports.VoterInformationGuide = functions.https.onRequest(app);
